title: Work Notes
description: "Technical notes and work-related content."
baseurl: ""
url: "https://ypyl.github.io/"
theme: minima

# Author info (used in footer)
author: Yauhen Pyl
email: yauhen.pyl@gmail.com

github_username: ypyl
linkedin_username: yauhenpyl
collections:
  tools:
    output: false
